---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: alpha-busybox
  name: alpha-busybox
  namespace: alpha
spec:
  replicas: 1
  selector:
    matchLabels:
      app: alpha-busybox
  template:
    metadata:
      labels:
        app: alpha-busybox
    spec:
      containers:
        - image: busybox
          name: busybox
          command:
            [
              "/bin/sh",
              "-c",
              "while true; do sleep 30; wget -qO- 'https://httpbin.org/uuid'; done",
            ]
          resources:
            requests:
              memory: 100Mi
              cpu: 100m
            limits:
              memory: 200Mi
              cpu: 100m
