apiVersion: v1
kind: Service
metadata:
  name: beta-nginx
  namespace: beta
spec:
  selector:
    app: beta-nginx
  ports:
    - name: nginx-port
      protocol: TCP
      port: 80
      targetPort: 80
